### ISSUE TITLE
Enhancement: Using sensu-flow with GitLab (gitlab-ci)

### ISSUE THREAD

**Issue by mhuysamen** [sensu/sensu-flow#29]
Here is an example of using sensu-flow with GitLab as a gitlab-ci step:

```yaml
stages:
  - deploy

.sensu_flow:
  image: registry.example.com/sensu/sensu-flow:v6.6.6-2
  variables:
    MATCHING_CONDITION: "== '$CI_PROJECT_NAME'"
    SENSU_BACKEND_URL: https://sensu-api.example.com
    SENSU_USER: sensu
    SENSU_PASSWORD: 'DontCopyM3!'
  script:
    - /sensuflow.sh

sensu_flow:
  extends: .sensu_flow
  stage: deploy
  variables:
    VERBOSE: "1"

```
