### ISSUE TITLE
Error: error pruning resources (/api/enterprise/prune/v1alpha): unauthorized to perform action  resources deleted

### ISSUE THREAD

**Issue by daswars** [sensu/sensu-flow#48]
For some time now I have been getting the following error:

What rights are missing here?
OS: CentOS 7 
Sensu Version: 6.10.0

```
checking to see if namespace exists on server
Namespace infrastructure
Pruning resources...

sensuctl prune checks,handlers,filters,mutators,assets,entities,hooks,roles,rolebindings,secrets/v1.Secret,bsm/v1.ServiceComponent --namespace infrastructure --label-selector "sensu.io/workflow == 'sensu-flow'" -r -f infrastructure | jq '. | length'
Error: error pruning resources (/api/enterprise/prune/v1alpha): unauthorized to perform action
 resources deleted
Creating/Updating r
```

Here are the permissions:

```
---
type: ClusterRole
api_version: core/v2
metadata:
  labels:
    sensu.io/managed_by: sensuctl
  name: sensu-flow
spec:
  rules:
  - resource_names: null
    resources:
    - namespaces
    - roles
    - rolebindings
    - assets
    - handlers
    - checks
    - hooks
    - filters
    - mutators
    - secrets
    - entities
    verbs:
    - get
    - list
    - create
    - update
    - delete

---
type: ClusterRoleBinding
api_version: core/v2
metadata:
  labels:
    sensu.io/managed_by: sensuctl
  name: sensu-flow
spec:
  role_ref:
    name: sensu-flow
    type: ClusterRole
  subjects:
  - name: sensu-flow
    type: Group

---
type: User
api_version: core/v2
metadata:
  name: sensu-flow
spec:
  disabled: false
  groups:
  - sensu-flow
  username: sensu-flow
  ```
